# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Lancs CSML
tagline:          ''
description:      'A place for ....'

author:
  name:           'Lancs'
  url:            http://www.lancaster.ac.uk/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
