# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Lancs CSML
tagline:          ' '
description:      'A place for ....'
url:              https://lu-csml.github.io
baseurl:          /

author:
  name:           ' '
  url:            https://twitter.com/mdo
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
